screen:
  width: 1024
  height: 768

grid:
  dim_grille: [6,7,2]
  force_full: False

camera:
  cam_area: [[192,256], [576,768]]
  cam_number: 1

button:
  hand_area_1: [[326, 900], [376, 1000]]
  hand_area_2: [[326, 30], [376, 80]]
  hand_threshold_1: 2_500 # pxl area
  hand_threshold_2: 2_000 # pxl area
  cooldown: 2


brick:
  min_brick_size: 1_500.0 # pxl area
  max_brick_size: 20_000.0 # pxl area

program:
  swap: True # swap between display panels
  swap_time: 3
  test_model: True

color:
  # hue: name
  -1: "Black"
  -2: "Steel"
  60: "Yellow"
  340: "Magenta"
  200: "Cyan"
  35: "Orange"
  0: "Red"
  80: "Green"

color_mat:
  # name: [conductivity, capacity, density, r_corrosion]
  #        W/(m*K),      J/(kg/K), kg/m^3
  "Black":   [0.00, 2000, 600, 1]
  "Blue":    [0.00, 2000, 600, .2]
  "Yellow":  [1.00, 2000, 600, .9]
  "Magenta": [20.0, 500, 2600, .9]
  "Cyan":    [0.02, 2000, 600, .3]
  "Orange":  [0.00, 2000, 600, .9]
  "Red":     [0.00, 2000, 600, .9]
  "Green":   [0.00, 2000, 600, .9]
  "Steel":   [20.0, 2000, 600, 1]

steel:
  temperature: 1600 # K
  cooling: False
  cooling_factor: 0.01 # K/s
